require 'scrapify/version'
require 'active_support/core_ext/class/attribute_accessors'
require 'nokogiri'
require 'open-uri'
require 'meta_define'
require 'scrapify/base'
require 'json'
require 'jsonify'
