require 'scrapify/version'
require 'active_support/core_ext/class/attribute_accessors'
require 'active_support/core_ext/hash/keys'
require 'nokogiri'
require 'uri'
require 'net/http'
require "net/https"
require "uri"
require 'scrapify/base'
require 'scrapify/scraper'
require 'scrapify/exceptions'
require 'json'
require 'jsonify'